import {Metadata} from "next";
import "./globals.css"
import HeadElement from "@/src/components/HeadElement/HeadElement";
import Header from "@/src/components/Header/Header";
import Footer from "../components/Footer/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={"flex flex-col"}>
        <HeadElement/>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}