import {Metadata} from "next";
import "./globals.css"
import HeadElement from "@/src/components/HeadElement/HeadElement";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={"flex h-full w-full flex-col"}>
        <HeadElement/>
        {children}
        </body>
        </html>
    );
}